spring.application.name=GalaxyStoreAPI

spring.datasource.url=jdbc:postgresql://localhost:5432/galaxy_store_db
spring.datasource.username=postgres
spring.datasource.password=Galaxy@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true